### ISSUE TITLE
Custom parser

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/steamdown#222]
This is a "meta-issue" for switching to custom parsing. These tasks should be completed before the switch to a custom parser. My current work is on the `rewrite` branch.

## Task list

- [x] Disable images (https://github.com/spenserblack/steamdown/issues/147)
- [x] Support tables (https://github.com/spenserblack/steamdown/issues/223)
- [x] Support `[hr][/hr]`
- [x] Support `[list]`
- [x] Support `[olist]`
- [x] Support `[h1]` - `[h6]`
- [x] Support `[spoiler]`
- [x] Support `[quote]` and `[quote author=author]` (note that all text within quotes can be parsed, e.g. nested quotes)
- [x] Support `[code]` (block only?) (https://github.com/spenserblack/steamdown/issues/221)
- [x] Support `[url=https://example.com]text[/url]`
- [x] Support `[i]italicized[/i]` (https://github.com/spenserblack/steamdown/issues/142)
- [x] Support `[u]underlined[/u]` (https://github.com/spenserblack/steamdown/issues/142)
- [x] Support `[b]bold[/b]`
- [x] Support `[strike]deleted[/strike]`
- [x] Support `[noparse][i]not italicized[/i][/noparse]`
- [x] Character escapes

Changing the syntax for spoilers (https://github.com/spenserblack/steamdown/issues/66) might occur during the switch to custom parsing, but can happen later.

Closes #137
